### ISSUE TITLE
Joplin to hexo link to header, feature missing

### ISSUE THREAD

**Issue by Eymeric65** [mark-magic/mark-magic#8]
Hello ! nice to meet you, you got a really useful tool !

I was tinkering with another joplin plugin that use yours in order to publish automatically pages to hexo site (actually it is only a UI for mark-magic). While tinkering I saw that mark-magic didn't support the link header way of joplin :
for exemple :
`:/738f25b6283a408aa2f517964cda0fc5#summary-of-git-strategy` 
when converting to hexo it gives :
`/p/5cb398f1511e45b095fa3e65c118dd62/:/content/738f25b6283a408aa2f517964cda0fc5#summary-of-git-strategy`.
instead of 
`/p/738f25b6283a408aa2f517964cda0fc5#summary-of-git-strategy`

I don't think it comes from the joplin plugin that wrap mark-magic. Maybe you could add a test to know if it comes from your library or it comes from the mdas-util ?

Best, 
Eymeric

**Comment by rxliuli** [comment]
Fixed. This is an issue from the mark-magic hexo plugin, which did not handle hash links correctly. Reference: <https://github.com/mark-magic/mark-magic/commit/11bddcc8fe2cd0d2086c110c1ffc534d578198a8>. It has now been fixed, and the Joplin Publisher plugin has released version 1.1.5, awaiting updates from the official Joplin repository.

**Comment by Eymeric65** [comment]
Didn't realized you were also the maintainer of Joplin Publisher ! Thanks for the fix, awesome plugin !
